version: "3.8"

services:
  mongodb:
    container_name: mongo-container
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis

  app:
    image: python:latest
    ports:
      - 8000:8000
    command: python src/main.py
    build:
      context: src
      dockerfile: dockerfile
    depends_on:
      - mongodb
    volumes:
      - .:/app

  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgres
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: lappis
      POSTGRES_PASSWORD: lappis
    
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: lappis
      MB_DB_PASS: lappis
      MB_DB_HOST: postgresql
    depends_on:
      - postgresql
    volumes:
      - .:/metabase