version: "3.8"

services:
  mongodb:
    container_name: mongo-container
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis